### ISSUE TITLE
tyranid throws an error if a collection doesn't exist

### ISSUE THREAD

**Issue by bsouthga** [tyranid-org/tyranid#90] opened 2017-08-30 22:10 UTC
to replicate, have a schema with dbName = 'accountLocks' but no collection in the db

**Comment by dimensia** [comment] 2017-09-26 19:13
Added test case to cover this and could not reproduce.  Possible it was fixed by something else in the past month.  Ben said to close it for now and he would re-open it if he ran into it again.

**Closed as completed by dimensia** 2017-09-26 19:13 UTC
Labels: bug
